#
# Mica server main configuration file.
# See documentation at: https://micadoc.obiba.org/en/latest/admin/configuration.html
#

# HTTP server configuration
server:
    port: 8082
    address: localhost

https:
    port: 8445

# Opal: data dictionaries, summaries and taxonomies
opal:
    url: https://localhost:8443
    username: administrator
    password: password

# Agate: user realm and application services configuration
agate:
    url: https://localhost:8444
    application:
        name: mica
        key: changeit

# Elasticsearch: search engine configuration
elasticsearch:
    dataNode: true
    clusterName: mica
    shards: 5
    replicas: 1
    settings: "http.enabled: false"
    maxConcurrentJoinQueries: 4
    concurrentJoinQueriesWaitTimeout: 30000

# Shiro: user directory configuration
shiro:
    password:
        nbHashIterations: 10000
        salt: mica

#
# Database connection
#

opalTaxonomies:
    defaultTermsSortOrder: "title"

spring:
    data:
        mongodb:
            uri: mongodb://localhost:27017/mica
    profiles: prod

sets:
  cleanup:
    # "<second> <minute> <hour> <day-of-month> <month> <day-of-week> <year>"
    # Current cron set to run every day at mid-night
    cron: "0 0 * * * ?"
